language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "pypy"
script: make test
install:
  - make
notifications:
  email: false
sudo: false
env: PYTHONWARNINGS=always::DeprecationWarning
