language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "pypy"
script: make test
install:
  - make
notifications:
  email: false
env: PYTHONWARNINGS=always::DeprecationWarning
matrix:
  include:
    - jdk: openjdk7
      python:
      install:
        - wget http://search.maven.org/remotecontent?filepath=org/python/jython-standalone/2.7-b4/jython-standalone-2.7-b4.jar -O jython.jar
        - java -jar jython.jar -m ensurepip
